[[tasks]]
name = "dcupb"
command = "docker compose up --build"
description = "KarimadoServer: Launch a preconfigured Rails development container"

[[tasks]]
name = "dcsh"
command = "docker compose exec rubydev {{ getvar_or_default 'CLI_ARGS' 'bash' }}"
description = "KarimadoServer: Exec a command in the Rails development container"
